/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorVideoIdRouteImport } from './routes/editor.$videoId'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppChannelsRouteImport } from './routes/_app.channels'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppVideosVideoIdRouteImport } from './routes/_app.videos.$videoId'
import { Route as AppSkillsSkillIdRouteImport } from './routes/_app.skills.$skillId'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorVideoIdRoute = EditorVideoIdRouteImport.update({
  id: '/editor/$videoId',
  path: '/editor/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosVideoIdRoute = AppVideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => AppVideosRoute,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppSkillsRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/channels': typeof AppChannelsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRouteWithChildren
  '/videos': typeof AppVideosRouteWithChildren
  '/editor/$videoId': typeof EditorVideoIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/videos/$videoId': typeof AppVideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/channels': typeof AppChannelsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRouteWithChildren
  '/videos': typeof AppVideosRouteWithChildren
  '/editor/$videoId': typeof EditorVideoIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/videos/$videoId': typeof AppVideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/channels': typeof AppChannelsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRouteWithChildren
  '/_app/videos': typeof AppVideosRouteWithChildren
  '/editor/$videoId': typeof EditorVideoIdRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/_app/videos/$videoId': typeof AppVideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/channels'
    | '/settings'
    | '/skills'
    | '/videos'
    | '/editor/$videoId'
    | '/agents/$agentId'
    | '/skills/$skillId'
    | '/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/channels'
    | '/settings'
    | '/skills'
    | '/videos'
    | '/editor/$videoId'
    | '/agents/$agentId'
    | '/skills/$skillId'
    | '/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agents'
    | '/_app/channels'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/videos'
    | '/editor/$videoId'
    | '/_app/agents/$agentId'
    | '/_app/skills/$skillId'
    | '/_app/videos/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EditorVideoIdRoute: typeof EditorVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$videoId': {
      id: '/editor/$videoId'
      path: '/editor/$videoId'
      fullPath: '/editor/$videoId'
      preLoaderRoute: typeof EditorVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos/$videoId': {
      id: '/_app/videos/$videoId'
      path: '/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof AppVideosVideoIdRouteImport
      parentRoute: typeof AppVideosRoute
    }
    '/_app/skills/$skillId': {
      id: '/_app/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppSkillsRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppSkillsRouteChildren {
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppVideosRouteChildren {
  AppVideosVideoIdRoute: typeof AppVideosVideoIdRoute
}

const AppVideosRouteChildren: AppVideosRouteChildren = {
  AppVideosVideoIdRoute: AppVideosVideoIdRoute,
}

const AppVideosRouteWithChildren = AppVideosRoute._addFileChildren(
  AppVideosRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppChannelsRoute: typeof AppChannelsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
  AppVideosRoute: typeof AppVideosRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppChannelsRoute: AppChannelsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRouteWithChildren,
  AppVideosRoute: AppVideosRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EditorVideoIdRoute: EditorVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
